INSERT INTO API_USER(EMAIL, FIRSTNAME, LASTNAME, LOGIN, PASSWORD, ROLE)
VALUES ( 'jan.bananek@test.pl', 'Jan', 'Bananek', 'JBananek', 'okon', 'BASIC_USER');


INSERT INTO BASIC_USER(ID) VALUES ( 1 );


INSERT INTO API_USER(EMAIL, FIRSTNAME, LASTNAME, LOGIN, PASSWORD, ROLE)
VALUES ( 'tom.wisnia@test.pl', 'Tom', 'Wisnia', 'TWisnia', 'okon2', 'BASIC_USER');

INSERT INTO API_USER(EMAIL, FIRSTNAME, LASTNAME, LOGIN, PASSWORD, ROLE)
VALUES ( 'jan.kowalski@test.pl', 'Jan', 'Kowalski', 'jkow', 'fsfsdf', 'BASIC_USER');

INSERT INTO API_USER(EMAIL, FIRSTNAME, LASTNAME, LOGIN, PASSWORD, ROLE)
VALUES ( 'john.doe@test.pl', 'John', 'Doe', 'jdo', 'fsdfsfsdq', 'BASIC_USER');

INSERT INTO API_USER(EMAIL, FIRSTNAME, LASTNAME, LOGIN, PASSWORD, ROLE)
VALUES ( 'jadwiga.nowak@test.pl', 'Jadwiga', 'Nowak', 'janow', 'qjfhcns', 'BASIC_USER');



INSERT INTO BASIC_USER(ID) VALUES ( 2 );

INSERT INTO BASIC_USER(ID) VALUES ( 3 );

INSERT INTO BASIC_USER(ID) VALUES ( 4 );

INSERT INTO BASIC_USER(ID) VALUES ( 5 );







INSERT INTO CATEGORY(NAME, VISIBLE) VALUES ('Sport', true);

INSERT INTO LOCATION(ALTITUDE, APARTMENT_NUMBER, CITY,LATITUDE, POSTCODE, STREET, STREET_NUMBER)
VALUES (0.0, '5A', 'Warsaw', 0.0, '92-100', 'Al. Jerozolimskie', '142');

INSERT INTO EVENT_INFO(DESCRIPTION, IS_CONFIRMATION_REQUIRED, NAME, START_DATE, CATEGORY_ID, LOCATION_ID)
VALUES ('Testowy opis', false, 'Testowy event', {ts '2012-09-17 18:47:52.69'}, 1, 1);

INSERT INTO EVENT_INFO(DESCRIPTION, IS_CONFIRMATION_REQUIRED, NAME, START_DATE, CATEGORY_ID, LOCATION_ID)
VALUES ('Internal', false, 'Testowy Internal event', {ts '2012-09-17 18:47:52.69'}, 1, 1);

INSERT INTO EVENT_INFO(DESCRIPTION, IS_CONFIRMATION_REQUIRED, NAME, START_DATE, CATEGORY_ID, LOCATION_ID)
VALUES ('Cyclic', false, 'Testowy Cyclic event', {ts '2012-09-17 18:47:52.69'}, 1, 1);

INSERT INTO EVENT_INFO(DESCRIPTION, IS_CONFIRMATION_REQUIRED, NAME, START_DATE, CATEGORY_ID, LOCATION_ID)
VALUES ('Internal', false, 'Testowy External event', {ts '2012-09-17 18:47:52.69'}, 1, 1);

INSERT INTO EVENT_OWNER(USER_ID) VALUES ( 1 );
INSERT INTO EVENT_OWNER(USER_ID) VALUES ( 2 );

INSERT INTO EVENT(EVENT_TYPE, LIMITED_PLACES, EVENT_INFO_ID, EVENT_OWNER_ID)
VALUES ('EVENT', 0, 1, 1);

INSERT INTO EVENTS_USERS_WITH_ACCESS(EVENT_ID, USER_ID) VALUES
(1, 1),
(1, 2),
(1, 3),
(1, 4);




INSERT INTO EVENT(EVENT_TYPE, LIMITED_PLACES, EVENT_INFO_ID, EVENT_OWNER_ID)
VALUES ('INTERNAL_EVENT', 0, 2, 1);

INSERT INTO INTERNAL_EVENT(IS_PRIVATE, ID, GROUP_ID)
VALUES ( TRUE, 2, NULL );

INSERT INTO EVENTS_USERS_WITH_ACCESS(EVENT_ID, USER_ID) VALUES
(2, 1),
(2, 2);



INSERT INTO EVENT(EVENT_TYPE, LIMITED_PLACES, EVENT_INFO_ID, EVENT_OWNER_ID)
VALUES ('CYCLIC_EVENT', 0, 3, 2);

INSERT INTO GROUP_OWNER(USER_ID, ID) VALUES( 1, 1 );

INSERT INTO GROUP_INFO(ID, NAME, DESCRIPTION) VALUES (1, 'wycieczkowanie', 'wycieczki bliższe i dalsze');

INSERT INTO API_GROUP(ID, GROUP_OWNER_ID, GROUP_INFO_ID) VALUES ( 1, 1, 1 );

INSERT INTO GROUPS_MEMBERS(GROUP_ID, BASIC_USER_ID) VALUES
(1, 2),
(1, 3),
(1, 4);


INSERT INTO INTERNAL_EVENT(IS_PRIVATE, ID, GROUP_ID)
VALUES ( FALSE, 3, 1 );

INSERT INTO CYCLIC_EVENT(FREQUENCY_IN_DAYS, NUMBER_OF_REPEATS, ID)
VALUES ( 2, 4, 3 );

INSERT INTO EVENTS_USERS_WITH_ACCESS(EVENT_ID, USER_ID) VALUES
(3, 2),
(3, 3),
(3, 4);




INSERT INTO EVENT(EVENT_TYPE, LIMITED_PLACES, EVENT_INFO_ID, EVENT_OWNER_ID)
VALUES ('EXTERNAL_EVENT', 0, 4, 1);

INSERT INTO EXTERNAL_EVENT(ID) VALUES (4);

INSERT INTO EVENTS_USERS_WITH_ACCESS(EVENT_ID, USER_ID) VALUES
(4, 1),
(4, 2),
(4, 3),
(4, 4);



INSERT INTO HASHTAG(HASHTAG_VALUE, OCCURRENCES, VISIBLE)
VALUES ( 'Piłka', 1, true);

INSERT INTO EVENTS_HASHTAGS(EVENT_ID, HASHTAG_ID)
values ( 3, 1 );

